name: Frontend Unit Tests

on:
  pull_request:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Frontend unit tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Install dependencies
        run: pnpm install

      - name: Setup turbo cache
        uses: ./.github/actions/turbo-cache

      - name: Test
        run: pnpm test
